name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook = 4
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 5
  # bind tornado version (websocket problems)
  - tornado = 4.5
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - nose
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - numpy
  - pandas
  - matplotlib
  - Keras
  - Keras-Applications
  - Keras-Preprocessing
  - IPython
  - scikit-learn
  - pip:
    - pgcontents
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
